# Generated by Django 3.2.5 on 2021-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='item_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
