# Generated by Django 3.2.5 on 2021-10-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_item_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='time',
        ),
    ]
